=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'date'

module Pdf4me

  class Document
    # JobId of Documents WorkingSet
    attr_accessor :job_id

    # DocumentId
    attr_accessor :document_id

    # Give filename inlcuding filetype
    attr_accessor :name

    # Returns the Status of the Document
    attr_accessor :doc_status

    # Description of pages
    attr_accessor :pages

    attr_accessor :doc_data

    attr_accessor :doc_metadata

    attr_accessor :doc_logs

    attr_accessor :notification


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'job_id' => :'jobId',
        :'document_id' => :'documentId',
        :'name' => :'name',
        :'doc_status' => :'docStatus',
        :'pages' => :'pages',
        :'doc_data' => :'docData',
        :'doc_metadata' => :'docMetadata',
        :'doc_logs' => :'docLogs',
        :'notification' => :'notification'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'job_id' => :'String',
        :'document_id' => :'String',
        :'name' => :'String',
        :'doc_status' => :'String',
        :'pages' => :'Array<Page>',
        :'doc_data' => :'String',
        :'doc_metadata' => :'DocMetadata',
        :'doc_logs' => :'Array<DocLog>',
        :'notification' => :'Notification'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'jobId')
        self.job_id = attributes[:'jobId']
      end

      if attributes.has_key?(:'documentId')
        self.document_id = attributes[:'documentId']
      end

      if attributes.has_key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.has_key?(:'docStatus')
        self.doc_status = attributes[:'docStatus']
      end

      if attributes.has_key?(:'pages')
        if (value = attributes[:'pages']).is_a?(Array)
          self.pages = value
        end
      end

      if attributes.has_key?(:'docData')
        self.doc_data = attributes[:'docData']
      end

      if attributes.has_key?(:'docMetadata')
        self.doc_metadata = attributes[:'docMetadata']
      end

      if attributes.has_key?(:'docLogs')
        if (value = attributes[:'docLogs']).is_a?(Array)
          self.doc_logs = value
        end
      end

      if attributes.has_key?(:'notification')
        self.notification = attributes[:'notification']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@doc_data.nil? && @doc_data !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        invalid_properties.push("invalid value for 'doc_data', must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@doc_data.nil? && @doc_data !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
      return true
    end

    # Custom attribute writer method with validation
    # @param [Object] doc_data Value to be assigned
    def doc_data=(doc_data)

      if !doc_data.nil? && doc_data !~ Regexp.new(/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/)
        fail ArgumentError, "invalid value for 'doc_data', must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/."
      end

      @doc_data = doc_data
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          job_id == o.job_id &&
          document_id == o.document_id &&
          name == o.name &&
          doc_status == o.doc_status &&
          pages == o.pages &&
          doc_data == o.doc_data &&
          doc_metadata == o.doc_metadata &&
          doc_logs == o.doc_logs &&
          notification == o.notification
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [job_id, document_id, name, doc_status, pages, doc_data, doc_metadata, doc_logs, notification].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Pdf4me.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
