=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::DocumentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DocumentApi' do
  before do
    # run before each test
    @instance = Pdf4me::DocumentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentApi' do
    it 'should create an instance of DocumentApi' do
      expect(@instance).to be_instance_of(Pdf4me::DocumentApi)
    end
  end

  # unit tests for drop_document
  # DropDocument
  # Drop a document from local FIlesystem or give a cloud storage from where the files will be downloaded.
  # @param [Hash] opts the optional parameters
  # @option opts [DropDocumentReq] :req 
  # @return [DropDocumentRes]
  describe 'drop_document test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for drop_document_0
  # ProduceDocuments
  # Produce the requested new Order Documents.
  # @param [Hash] opts the optional parameters
  # @option opts [ProduceDocuments] :req 
  # @return [ProduceDocumentsRes]
  describe 'drop_document_0 test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_document
  # GetDocument
  # Get the content of a document in its full datastructure and content.
  # @param [Hash] opts the optional parameters
  # @option opts [GetDocumentReq] :req 
  # @return [GetDocumentRes]
  describe 'get_document test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_documents
  # GetDocuments
  # Get the workingset of documents by the JobId.
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @return [GetDocumentRes]
  describe 'get_documents test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
