=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::ImageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ImageApi' do
  before do
    # run before each test
    @instance = Pdf4me::ImageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ImageApi' do
    it 'should create an instance of ImageApi' do
      expect(@instance).to be_instance_of(Pdf4me::ImageApi)
    end
  end

  # unit tests for create_images
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateImages] :req 
  # @return [CreateImagesRes]
  describe 'create_images test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_thumbnail
  # 
  # 
  # @param width 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :page_nr 
  # @option opts [String] :image_format 
  # @option opts [String] :file 
  # @return [File]
  describe 'create_thumbnail test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
