=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::ManagementApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ManagementApi' do
  before do
    # run before each test
    @instance = Pdf4me::ManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ManagementApi' do
    it 'should create an instance of ManagementApi' do
      expect(@instance).to be_instance_of(Pdf4me::ManagementApi)
    end
  end

  # unit tests for api_usage
  # ApiUsage
  # Give an overview of current ApiUsage and if its payment.
  # @param [Hash] opts the optional parameters
  # @return [ApiUsageRes]
  describe 'api_usage test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for version
  # Version
  # A simple method to get the current Version
  # @param [Hash] opts the optional parameters
  # @return [VersionRes]
  describe 'version test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
