=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::MergeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MergeApi' do
  before do
    # run before each test
    @instance = Pdf4me::MergeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MergeApi' do
    it 'should create an instance of MergeApi' do
      expect(@instance).to be_instance_of(Pdf4me::MergeApi)
    end
  end

  # unit tests for merge
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Merge] :req 
  # @return [MergeRes]
  describe 'merge test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for merge2_pdfs
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file1 
  # @option opts [String] :file2 
  # @return [File]
  describe 'merge2_pdfs test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
