=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::OptimizeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OptimizeApi' do
  before do
    # run before each test
    @instance = Pdf4me::OptimizeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OptimizeApi' do
    it 'should create an instance of OptimizeApi' do
      expect(@instance).to be_instance_of(Pdf4me::OptimizeApi)
    end
  end

  # unit tests for optimize
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Optimize] :req 
  # @return [OptimizeRes]
  describe 'optimize test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for optimize_by_profile
  # 
  # 
  # @param profile 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @return [File]
  describe 'optimize_by_profile test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
