=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::PdfAApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PdfAApi' do
  before do
    # run before each test
    @instance = Pdf4me::PdfAApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PdfAApi' do
    it 'should create an instance of PdfAApi' do
      expect(@instance).to be_instance_of(Pdf4me::PdfAApi)
    end
  end

  # unit tests for create_pdf_a
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :pdf_compliance 
  # @option opts [String] :file 
  # @return [File]
  describe 'create_pdf_a test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for pdf_a
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [CreatePdfA] :req 
  # @return [CreatePdfARes]
  describe 'pdf_a test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
