=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::SplitApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SplitApi' do
  before do
    # run before each test
    @instance = Pdf4me::SplitApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SplitApi' do
    it 'should create an instance of SplitApi' do
      expect(@instance).to be_instance_of(Pdf4me::SplitApi)
    end
  end

  # unit tests for split
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Split] :req 
  # @return [SplitRes]
  describe 'split test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for split_by_page_nr
  # 
  # 
  # @param page_nr 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :file 
  # @return [SplitRes]
  describe 'split_by_page_nr test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
