=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Pdf4me::StampApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StampApi' do
  before do
    # run before each test
    @instance = Pdf4me::StampApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StampApi' do
    it 'should create an instance of StampApi' do
      expect(@instance).to be_instance_of(Pdf4me::StampApi)
    end
  end

  # unit tests for stamp
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [Stamp] :req 
  # @return [StampRes]
  describe 'stamp test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for text_stamp
  # 
  # 
  # @param align_x 
  # @param align_y 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :text 
  # @option opts [String] :pages 
  # @option opts [String] :file 
  # @return [File]
  describe 'text_stamp test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
