=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pdf4me::ConvertToPdfAction
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ConvertToPdfAction' do
  before do
    # run before each test
    @instance = Pdf4me::ConvertToPdfAction.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConvertToPdfAction' do
    it 'should create an instance of ConvertToPdfAction' do
      expect(@instance).to be_instance_of(Pdf4me::ConvertToPdfAction)
    end
  end
  describe 'test attribute "pdf_conformance"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["pdf17", "pdfA1", "pdfA2", "pdfA3"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.pdf_conformance = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "conversion_mode"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["fast", "detailed"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.conversion_mode = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "custom_properties"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

