=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pdf4me::ProduceOutput
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProduceOutput' do
  before do
    # run before each test
    @instance = Pdf4me::ProduceOutput.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProduceOutput' do
    it 'should create an instance of ProduceOutput' do
      expect(@instance).to be_instance_of(Pdf4me::ProduceOutput)
    end
  end
  describe 'test attribute "file_type"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["undef", "pdf", "zip"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.file_type = value }.not_to raise_error
       #end
    end
  end

end

