=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Pdf4me::SignatureConfig
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SignatureConfig' do
  before do
    # run before each test
    @instance = Pdf4me::SignatureConfig.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SignatureConfig' do
    it 'should create an instance of SignatureConfig' do
      expect(@instance).to be_instance_of(Pdf4me::SignatureConfig)
    end
  end
end

