=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

# Common files
require 'pdf4me/api_client'
require 'pdf4me/api_error'
require 'pdf4me/version'
require 'pdf4me/configuration'

# Models
require 'pdf4me/models/action_flow'
require 'pdf4me/models/api_usage_res'
require 'pdf4me/models/archive_config'
require 'pdf4me/models/archive_job_req'
require 'pdf4me/models/archive_job_res'
require 'pdf4me/models/color'
require 'pdf4me/models/convert_to_pdf'
require 'pdf4me/models/convert_to_pdf_action'
require 'pdf4me/models/convert_to_pdf_res'
require 'pdf4me/models/create_images'
require 'pdf4me/models/create_images_res'
require 'pdf4me/models/create_pdf_a'
require 'pdf4me/models/create_pdf_a_res'
require 'pdf4me/models/custom_cms_config'
require 'pdf4me/models/doc_action'
require 'pdf4me/models/doc_log'
require 'pdf4me/models/doc_metadata'
require 'pdf4me/models/document'
require 'pdf4me/models/drop_document_req'
require 'pdf4me/models/drop_document_res'
require 'pdf4me/models/execution_trigger'
require 'pdf4me/models/extract'
require 'pdf4me/models/extract_action'
require 'pdf4me/models/extract_res'
require 'pdf4me/models/get_document_list_res'
require 'pdf4me/models/get_document_req'
require 'pdf4me/models/get_document_res'
require 'pdf4me/models/i_form_file'
require 'pdf4me/models/image'
require 'pdf4me/models/image_action'
require 'pdf4me/models/job'
require 'pdf4me/models/job_config'
require 'pdf4me/models/job_config_res'
require 'pdf4me/models/key_value_pair_string_object'
require 'pdf4me/models/key_value_pair_string_string'
require 'pdf4me/models/merge'
require 'pdf4me/models/merge_action'
require 'pdf4me/models/merge_res'
require 'pdf4me/models/notification'
require 'pdf4me/models/ocr_action'
require 'pdf4me/models/optimize'
require 'pdf4me/models/optimize_action'
require 'pdf4me/models/optimize_res'
require 'pdf4me/models/page'
require 'pdf4me/models/page_selection'
require 'pdf4me/models/pdf4me_action'
require 'pdf4me/models/pdf4me_document'
require 'pdf4me/models/pdf4me_exception'
require 'pdf4me/models/pdf_a_action'
require 'pdf4me/models/pdf_font'
require 'pdf4me/models/pricing'
require 'pdf4me/models/produce_documents'
require 'pdf4me/models/produce_documents_res'
require 'pdf4me/models/produce_output'
require 'pdf4me/models/rgb_set'
require 'pdf4me/models/recognize_document'
require 'pdf4me/models/recognize_document_res'
require 'pdf4me/models/rectangle'
require 'pdf4me/models/rotate'
require 'pdf4me/models/run_job_res'
require 'pdf4me/models/signature_config'
require 'pdf4me/models/split'
require 'pdf4me/models/split_action'
require 'pdf4me/models/split_res'
require 'pdf4me/models/stamp'
require 'pdf4me/models/stamp_action'
require 'pdf4me/models/stamp_res'
require 'pdf4me/models/storage_folder'
require 'pdf4me/models/text'
require 'pdf4me/models/transform'
require 'pdf4me/models/translate'
require 'pdf4me/models/user_fingerprint'
require 'pdf4me/models/version_res'

# APIs
require 'pdf4me/api/convert_api'
require 'pdf4me/api/document_api'
require 'pdf4me/api/extract_api'
require 'pdf4me/api/image_api'
require 'pdf4me/api/job_api'
require 'pdf4me/api/management_api'
require 'pdf4me/api/merge_api'
require 'pdf4me/api/ocr_api'
require 'pdf4me/api/optimize_api'
require 'pdf4me/api/pdf_a_api'
require 'pdf4me/api/split_api'
require 'pdf4me/api/stamp_api'

module Pdf4me
  class << self
    # Customize default settings for the SDK using block.
    #   Pdf4me.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
