=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module Pdf4me
  class ExtractApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Extract] :req 
    # @return [ExtractRes]
    def extract(opts = {})
      data, _status_code, _headers = extract_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Extract] :req 
    # @return [Array<(ExtractRes, Fixnum, Hash)>] ExtractRes data, response status code and response headers
    def extract_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ExtractApi.extract ..."
      end
      # resource path
      local_var_path = "/Extract/Extract"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json', 'application/bson'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json-patch+json', 'application/json', 'text/json', 'application/*+json', 'application/bson'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'req'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'ExtractRes')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ExtractApi#extract\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page_nrs 
    # @option opts [String] :file 
    # @return [File]
    def extract_pages(opts = {})
      data, _status_code, _headers = extract_pages_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page_nrs 
    # @option opts [String] :file 
    # @return [Array<(File, Fixnum, Hash)>] File data, response status code and response headers
    def extract_pages_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ExtractApi.extract_pages ..."
      end
      # resource path
      local_var_path = "/Extract/ExtractPages"

      # query parameters
      query_params = {}
      # query_params[:'pageNrs'] = opts[:'page_nrs'] if !opts[:'page_nrs'].nil?
      # query_params[:'file'] = opts[:'file'] if !opts[:'file'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/octet-stream'])
      header_params['Content-Type'] ='multipart/form-data'

      # form parameters
      form_params = {
        pageNrs: opts[:page_nrs],
        file: opts[:file]
      }

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'File')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ExtractApi#extract_pages\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
