=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module Pdf4me
  class ImageApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [CreateImages] :req 
    # @return [CreateImagesRes]
    def create_images(opts = {})
      data, _status_code, _headers = create_images_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [CreateImages] :req 
    # @return [Array<(CreateImagesRes, Fixnum, Hash)>] CreateImagesRes data, response status code and response headers
    def create_images_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ImageApi.create_images ..."
      end
      # resource path
      local_var_path = "/Image/CreateImages"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json', 'application/bson'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json-patch+json', 'application/json', 'text/json', 'application/*+json', 'application/bson'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'req'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'CreateImagesRes')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ImageApi#create_images\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param width 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page_nr 
    # @option opts [String] :image_format 
    # @option opts [String] :file 
    # @return [File]
    def create_thumbnail(width, opts = {})
      data, _status_code, _headers = create_thumbnail_with_http_info(width, opts)
      return data
    end

    # 
    # 
    # @param width 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :page_nr 
    # @option opts [String] :image_format 
    # @option opts [String] :file 
    # @return [Array<(File, Fixnum, Hash)>] File data, response status code and response headers
    def create_thumbnail_with_http_info(width, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: ImageApi.create_thumbnail ..."
      end
      # verify the required parameter 'width' is set
      if @api_client.config.client_side_validation && width.nil?
        fail ArgumentError, "Missing the required parameter 'width' when calling ImageApi.create_thumbnail"
      end
      # resource path
      local_var_path = "/Image/CreateThumbnail"

      # query parameters
      query_params = {}


      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/octet-stream'])
      header_params['Content-Type'] ='multipart/form-data'

      # form parameters
      form_params = {}
      form_params[:'width'] = width
      form_params[:'pageNr'] = opts[:'page_nr'] if !opts[:'page_nr'].nil?
      form_params[:'imageFormat'] = opts[:'image_format'] if !opts[:'image_format'].nil?
      form_params[:'file'] = opts[:'file'] if !opts[:'file'].nil?

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'File')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ImageApi#create_thumbnail\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
