=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module Pdf4me
  class MergeApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Merge] :req 
    # @return [MergeRes]
    def merge(opts = {})
      data, _status_code, _headers = merge_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Merge] :req 
    # @return [Array<(MergeRes, Fixnum, Hash)>] MergeRes data, response status code and response headers
    def merge_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MergeApi.merge ..."
      end
      # resource path
      local_var_path = "/Merge/Merge"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json', 'application/bson'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json-patch+json', 'application/json', 'text/json', 'application/*+json', 'application/bson'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'req'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'MergeRes')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MergeApi#merge\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file1 
    # @option opts [String] :file2 
    # @return [File]
    def merge2_pdfs(opts = {})
      data, _status_code, _headers = merge2_pdfs_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file1 
    # @option opts [String] :file2 
    # @return [Array<(File, Fixnum, Hash)>] File data, response status code and response headers
    def merge2_pdfs_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: MergeApi.merge2_pdfs ..."
      end
      # resource path
      local_var_path = "/Merge/Merge2Pdfs"

      # query parameters
      query_params = {}
      # query_params[:'file1'] = opts[:'file1'] if !opts[:'file1'].nil?
      # query_params[:'file2'] = opts[:'file2'] if !opts[:'file2'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/octet-stream'])
      header_params['Content-Type'] ='multipart/form-data'

      # form parameters
      form_params = {
        file1: opts[:file1],
        file2: opts[:file2]
      }

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'File')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MergeApi#merge2_pdfs\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
