=begin
#DmsApi

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.0

=end

require "uri"

module Pdf4me
  class SplitApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Split] :req 
    # @return [SplitRes]
    def split(opts = {})
      data, _status_code, _headers = split_with_http_info(opts)
      return data
    end

    # 
    # 
    # @param [Hash] opts the optional parameters
    # @option opts [Split] :req 
    # @return [Array<(SplitRes, Fixnum, Hash)>] SplitRes data, response status code and response headers
    def split_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SplitApi.split ..."
      end
      # resource path
      local_var_path = "/Split/Split"

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json', 'application/bson'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json-patch+json', 'application/json', 'text/json', 'application/*+json', 'application/bson'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(opts[:'req'])
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'SplitRes')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SplitApi#split\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # 
    # 
    # @param page_nr 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file 
    # @return [SplitRes]
    def split_by_page_nr(page_nr, opts = {})
      data, _status_code, _headers = split_by_page_nr_with_http_info(page_nr, opts)
      return data
    end

    # 
    # 
    # @param page_nr 
    # @param [Hash] opts the optional parameters
    # @option opts [String] :file 
    # @return [Array<(SplitRes, Fixnum, Hash)>] SplitRes data, response status code and response headers
    def split_by_page_nr_with_http_info(page_nr, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug "Calling API: SplitApi.split_by_page_nr ..."
      end
      # verify the required parameter 'page_nr' is set
      if @api_client.config.client_side_validation && page_nr.nil?
        fail ArgumentError, "Missing the required parameter 'page_nr' when calling SplitApi.split_by_page_nr"
      end
      # resource path
      local_var_path = "/Split/SplitByPageNr"

      # query parameters
      query_params = {}
      # query_params[:'pageNr'] = page_nr
      # query_params[:'file'] = opts[:'file'] if !opts[:'file'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['text/plain', 'application/json', 'text/json', 'application/bson'])
      header_params['Content-Type'] ='multipart/form-data'

      # form parameters
      form_params = {
        pageNr: page_nr,
        file: opts[:file]
      }

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'SplitRes')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: SplitApi#split_by_page_nr\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
